on: push
name: Validate API swagger definition file
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Get OpenAPI/Swagger definition file
        uses: actions/checkout@v4
      - name: Validate OpenAPI/Swagger definition file
        uses: mbowman100/swagger-validator-action@master
        with:
          files: swagger.json
